import { config } from "dotenv";
config();
export const configs = {
  PORT: process.env.PORT,
  DB_URL: process.env.DB_URL,

  SALT: +process.env.SALT,

  JWT_CANDIDATE_ACCESS_SECRET: process.env.JWT_CANDIDATE_ACCESS_SECRET,
  JWT_CANDIDATE_REFRESH_SECRET: process.env.JWT_CANDIDATE_REFRESH_SECRET,

  JWT_HR_ACCESS_SECRET: process.env.JWT_HR_ACCESS_SECRET,
  JWT_HR_REFRESH_SECRET: process.env.JWT_HR_REFRESH_SECRET,

  JWT_COMPANY_ACCESS_SECRET: process.env.JWT_COMPANY_ACCESS_SECRET,
  JWT_COMPANY_REFRESH_SECRET: process.env.JWT_COMPANY_REFRESH_SECRET,
};
